### ISSUE TITLE
Seems to override launch options as opposed to append to t hem.

### ISSUE THREAD

**Issue by char** [SilverCory/MojangPls#1]
After the fix I can add it to the README of MojangBlacklistBypass.jar

**Comment by SilverCory** [comment]
I can't recreate this? Tried several things.

**Comment by char** [comment]
Happens in this video: https://www.youtube.com/watch?v=o5TYtXfjqVk
I use the auto installer at 3:20 and onwards

**Comment by SilverCory** [comment]
If there are no arguments (it's not checked), instead of adding potential arguments that may make the client unusable it instead only adds the javaagent argument.

It also doesn't add the javaagent if there is already one existing. :)
